---
- name: Configuration for H3C devices from Capacita-Rework repository
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Verifying if device is online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 5
        state: started
      delegate_to: localhost
      ignore_errors: yes

    - name: Enabling FTP server on the device...
      comware_ftp:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        state: "enable"
      ignore_errors: yes

    - name: Download the configuration content from FTP to the device
      comware_file_copy:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        file: "/ansible/configs/newstartup.cfg"
        remote_path: "flash:/newstartup3.cfg"
      ignore_errors: yes

    - name: Changing the Next Startup configuration file
      comware_startup:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        nextstartupfile: "flash:/newstartup3.cfg"
      ignore_errors: yes

    - name: Verifying the configuration of the Uploaded file before restart
      comware_startup:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        filename: "flash:/newstartup3.cfg"
        show_file: "/ansible/configs/newstartup_copy3.cfg"
      ignore_errors: yes

    - name: Rebooting the device
      comware_reboot:
        reboot: true
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      ignore_errors: yes

