- name: Check hosts connectivity
  hosts: all
  gather_facts: no

  tasks:
    - name: Check if hosts are online
      ping:
      register: result
      ignore_errors: true

    - name: Apply main playbook if host is online
      include_tasks: switch.yml
      when: result.changed == true