---
- name: Wait util a host be online... 
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH connection... 
      wait_for_connection:
        timeout: 300

- name: Configuration for H3C devices from Capacita-Rework repository
  hosts: alll
  gather_facts: no
  connection: local

  tasks:
    - name: Creating a new file using save command...
      comware_save:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        filename: "newstartup.cfg"

    - name: Enabling FTP server on the device...
      comware_ftp:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        state: "enable"

    - name: Download the configuration content from FTP to the device 
      comware_file_copy:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        file: "/ansible/configs/newstartup.cfg"
        remote_path: "flash:/newstartup2.cfg"

    - name: Changing the Next Startup configuration file
      comware_startup:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        nextstartupfile: "flash:/newstartup2.cfg"

    - name: Verifying the configuration of the Uploaded file before restart
      comware_startup:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        filename: "flash:/newstartup2.cfg"
        show_file: "/ansible/configs/newstartup_copy2.cfg"

    - name: Rebooting the device
      comware_reboot:
        reboot: true
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

