# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

# Use networkboot DHCP image as base:
FROM networkboot/dhcpd:1.3.0

# Installing network packages; 
RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools \
    supervisor \
    && rm -rf /var/lib/apt/lists/*

# Copy the configuration file to the container:
COPY docker/startup-dhcpd.sh /usr/local/bin/startup.sh

# Set the file as executable:
RUN chmod +x /usr/local/bin/startup.sh

# Configuring Supervisord: 
RUN mkdir -p /var/log/supervisor /etc/supervisor/conf.d
COPY ./docker/supervisord-dhcpd.conf /etc/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
