# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

# Use networkboot DHCP image as base:
FROM networkboot/dhcpd:1.3.0

# Installing network packages; 
RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools \
    supervisor \
    && rm -rf /var/lib/apt/lists/*

RUN touch /var/lib/dhcp/dhcpd.leases

RUN chown root:root /var/lib/dhcp/dhcpd.leases

RUN chmod 664 /var/lib/dhcp/dhcpd.leases

# Copy the configuration file to the container:
#COPY serverDHCP/startup.sh /usr/local/bin/startup.sh

# Set the file as executable:
#RUN chmod +x /usr/local/bin/startup.sh

# Start the DHCP server and keep it running:
#CMD ["/usr/local/bin/startup.sh"]

RUN mkdir -p /var/log/supervisor /etc/supervisor/conf.d

COPY ./supervisor-dhcpd.conf /etc/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
